[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[[services]]
mounts = ["uploads"]

[environment]
DATABASE_URL = "${{Postgres.DATABASE_URL}}"

